#!/usr/bin/env bash
set -euo pipefail

canonical_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
if [[ -f "${canonical_root}/.env.local" ]]; then
  # Generated by setup.sh and deliberately excluded from the release archive.
  # shellcheck disable=SC1091
  source "${canonical_root}/.env.local"
fi

linux_root="${X_MINIMAXH3_RUNTIME_ROOT:-${H3_LINUX_RUNTIME_ROOT:-/root/x-minimaxh3-runtime}}"
linux_worktree="${linux_root}/worktree"
python_bin="${H3_SERVE_PYTHON:-${canonical_root}/runtime/venv/bin/python}"
model_root="${H3_SERVE_MODEL_DIR:-${canonical_root}/models}"
minimax_source="${H3_SERVE_MINIMAX_SOURCE:-${canonical_root}/runtime/vendor/MiniMax-H3}"
lightx_source="${H3_SERVE_LIGHTX_SOURCE:-${canonical_root}/runtime/vendor/LightX2V}"
default_service_launch=0
if (($# == 0)); then
  default_service_launch=1
fi

[[ "${linux_root}" != "/" && "${linux_root}" != "/root" ]] || {
  echo "Refusing unsafe Linux runtime root: ${linux_root}" >&2
  exit 2
}

# Ordinary launches always refresh the Linux-native source mirror. Developer
# commands can opt in or out explicitly with H3_LINUX_SYNC=1/0.
sync_mode="${H3_LINUX_SYNC:-auto}"
if [[ "${sync_mode}" == "1" \
      || ("${sync_mode}" == "auto" && "${default_service_launch}" == "1") \
      || ! -d "${linux_worktree}/h3serve" ]]; then
  X_MINIMAXH3_RUNTIME_ROOT="${linux_root}" \
    "${canonical_root}/scripts/sync_linux_runtime.sh"
fi

[[ -x "${python_bin}" ]] || {
  echo "Missing configured H3 Python: ${python_bin}. Run ./setup.sh first." >&2
  exit 1
}
[[ -d "${linux_worktree}/h3serve" ]] || {
  echo "Linux runtime mirror is incomplete: ${linux_worktree}" >&2
  exit 1
}
[[ -d "${minimax_source}" ]] || {
  echo "Missing configured MiniMax-H3 source: ${minimax_source}" >&2
  exit 1
}
[[ -d "${lightx_source}" ]] || {
  echo "Missing configured LightX2V source: ${lightx_source}" >&2
  exit 1
}

mkdir -p "${linux_root}/cache/"{cuda,huggingface,pycache,torch,torchinductor,triton,xdg} \
  "${linux_root}/tmp" "${linux_worktree}/runtime"

export CUDA_HOME="${CUDA_HOME:-/usr/local/cuda-13.3}"
export CUDA_CACHE_PATH="${CUDA_CACHE_PATH:-${linux_root}/cache/cuda}"
export HF_HOME="${HF_HOME:-${linux_root}/cache/huggingface}"
export PYTHONPYCACHEPREFIX="${PYTHONPYCACHEPREFIX:-${linux_root}/cache/pycache}"
export TORCH_HOME="${TORCH_HOME:-${linux_root}/cache/torch}"
export TORCHINDUCTOR_CACHE_DIR="${TORCHINDUCTOR_CACHE_DIR:-${linux_root}/cache/torchinductor}"
export TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-${linux_root}/cache/triton}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-${linux_root}/cache/xdg}"
export TMPDIR="${TMPDIR:-${linux_root}/tmp}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
export PATH="${CUDA_HOME}/bin:${PATH}"
export H3_SERVE_PYTHON="${python_bin}"
export H3_SERVE_RUNTIME_DIR="${linux_worktree}/runtime"
export H3_SERVE_MODEL_DIR="${model_root}"
export H3_SERVE_MINIMAX_SOURCE="${minimax_source}"
export H3_SERVE_LIGHTX_SOURCE="${lightx_source}"
export H3_SERVE_DATA_DIR="${H3_SERVE_DATA_DIR:-${canonical_root}/data}"
export H3_SERVE_OUTPUT_DIR="${H3_SERVE_OUTPUT_DIR:-${canonical_root}/output}"
if [[ -x "${canonical_root}/runtime/flashvsr-venv/bin/python" ]]; then
  export H3_SERVE_FLASHVSR_PYTHON="${H3_SERVE_FLASHVSR_PYTHON:-${canonical_root}/runtime/flashvsr-venv/bin/python}"
fi
export PYTHONPATH="${linux_worktree}:${linux_worktree}/backends/turbo/vendor${H3_NATIVE_SPARGE_BUILD_DIR:+:${H3_NATIVE_SPARGE_BUILD_DIR}}${PYTHONPATH:+:${PYTHONPATH}}"

cd "${linux_worktree}"
if (($# == 0)); then
  set -- bash scripts/start.sh
fi
case "$1" in
  python) shift; exec "${python_bin}" "$@" ;;
  bash) shift; exec /usr/bin/env bash "$@" ;;
  *) exec "$@" ;;
esac
